[package]
name = "provn-sdk-python"
version = "0.3.3"
edition = "2021"
description = "Python bindings for Provncloud SDK"
license = "MIT"
readme = "README.md"
repository = "https://github.com/provnai/provn-sdk"
homepage = "https://github.com/provnai/provn-sdk"

[lib]
name = "provn_sdk"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20.0", features = ["extension-module"] }
provn_sdk_core = { package = "provn-sdk", path = "../rust", default-features = false, features = ["std"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
ed25519-dalek = "2.2.0"
