name: Python CI

on:
  push:
    branches: [ main ]
    paths:
      - 'python/**'
      - 'spec/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'python/**'
      - 'spec/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    defaults:
      run:
        working-directory: ./python
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: python -m pip install --upgrade pip pytest maturin
      - name: Build and Install SDK
        run: maturin develop --release
      - name: Run tests
        run: pytest -v
